version: 'version 1.0.0'
services:
  scbm-db:
    image: postgres:14.1-alpine
    container_name: scbm-db
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/scbm/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  scbm-api:
    image: scbm-api:latest
    container_name: scbm-api
    build:
      context: /home/drale/Downloads/projects/web/SCBM/api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@scbm-db:5432/postgres
      - PORT=5000
      - NODE_ENV=development
      - VERSION=V1.0.0
      - JWT_SECRET=fnAK562ffGngrj
      - SENDGRID_API_KEY=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
    depends_on:
      scbm-db:
        condition: service_healthy
    volumes:
      - /tmp/SCBM/api/npm-cache:/root/.npm:z
      - /home/drale/Downloads/projects/web/SCBM/api/src:/usr/src/app/src:z
      - /home/drale/Downloads/projects/web/SCBM/api/node_modules:/usr/src/app/node_modules:z

volumes:
  db:
    driver: local