import { type NextPage } from "next";
import Head from "next/head";
import { Dispatch, SetStateAction } from "react";
import AccountForm from "../components/Account/AccountForm";

type props = {
    setLoading: Dispatch<SetStateAction<{
        isLoading: boolean;
        message: string;
    }>>
}

export const getStaticProps = () => {
    return {
        props: {}
    }
}

const Account: NextPage = ({setLoading}:props) => {

  return (
    <>
      <Head>
        <title>My account</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-black pb-6">Account</h1>
      <AccountForm setLoading={setLoading} />
    </>
  );
};

export default Account;
