FROM node:18-alpine3.15

WORKDIR /usr/src/app

COPY package.json ./

COPY tsconfig.json ./

# RUN npm install

COPY ./ ./

RUN npx prisma generate --schema ./prisma/schema.prisma

EXPOSE 5000

EXPOSE 5555

CMD [ "npm", "run", "start:dev" ]