FROM nikolaik/python-nodejs

WORKDIR /usr/src/app

COPY package.json ./

COPY tsconfig.json ./

COPY ./ ./

RUN mkdir -p /home/drale/Downloads/projects/web/SCBM/api/src/storage/images

RUN apt-get update && apt-get install -y libgl1 pkg-config libhdf5-dev gcc

RUN pip install --upgrade pip setuptools wheel

RUN pip3 install cmake numpy Click Pillow opencv-python

RUN cd && git clone https://github.com/davisking/dlib.git

RUN cd && cd dlib && python3 setup.py install

RUN pip install --upgrade pip setuptools

RUN cd && git clone https://github.com/DraouiBilal/face_recognition.git

RUN cd && cd face_recognition && python setup.py install

EXPOSE 5000

EXPOSE 5555

CMD [ "npm", "run", "start:dev" ]